AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway REST API'

Parameters:
  ApiName:
    Type: String
    Description: 'Name for the API Gateway REST API'
    MinLength: 1
    MaxLength: 128
    Default: Api
  SwaggerDefinition:
    Type: String
    Description: 'Swagger JSON definition for the API Gateway'
    Default: '{}'

Resources:
  MyApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Ref ApiName
      FailOnWarnings: 'true'
      Body: !Ref SwaggerDefinition

Outputs:
  ApiId:
    Description: 'ID of the API Gateway REST API'
    Value: !Ref Api
