AWSTemplateFormatVersion: "2010-09-09"
Description: Load Balancer Stack

Resources:
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyLoadBalancer
      Subnets:
        - "subnet-0123456789abcdef0"
        - "subnet-0123456789abcdef1"
