AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for DocumentDB Cluster

Parameters:
  ClusterName:
    Description: Name for the DocumentDB cluster
    Type: String
    MinLength: 1
    MaxLength: 255
    ConstraintDescription: The cluster name must be between 1 and 255 characters.

  NumberOfInstances:
    Description: "Number of instances in the DocumentDB cluster"
    Type: "Number"
    Default: 1
    MinValue: 1
    MaxValue: 10

  MasterUsername:
    Description: Master username for the DocumentDB cluster
    Type: String
    MinLength: 1
    MaxLength: 63
    Default: myadminuser
    ConstraintDescription: The master username must be between 1 and 63 characters.

  MasterUserPassword:
    Description: Master user password for the DocumentDB cluster
    Type: String
    MinLength: 1
    NoEcho: true
    ConstraintDescription: The password must be at least 1 character long.

  DBInstanceClass:
    Description: "Instance Class of the DocumentDB cluster"
    Type: String
    MinLength: 1
    MaxLength: 80
    ConstraintDescription: The cluster instance must be between 1 and 80 characters.

Resources:
  DocumentDBSubnetGroup:
    Type: "AWS::DocDB::DBSubnetGroup"
    Properties:
      DBSubnetGroupName: DocDBSubnetGroup
      SubnetIds:
        - subnet-05dc13506a5563adc  # Specify the IDs of your subnets
        - subnet-0db9b3b2deabbfb0a
        # Add more subnet IDs as needed
      DBSubnetGroupDescription: Subnet group for DocumentDB
      
  DocumentDBCluster:
    Type: "AWS::DocDB::DBCluster"
    Properties:
      DBClusterIdentifier: !Ref ClusterName
      EngineVersion: "4.0"
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DocumentDBSubnetGroup
      VpcSecurityGroupIds:
        - sg-0308df5e08a2aa143  # Specify the appropriate security group ID
      AvailabilityZones:
        - ap-southeast-1a
        - ap-southeast-1b
      BackupRetentionPeriod: 7  # Update with your desired backup retention period
      StorageEncrypted: true

  DocumentDBInstance:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DocumentDBCluster
      DBInstanceClass: !Ref DBInstanceClass
      AutoMinorVersionUpgrade: true
      
Outputs:
  DocumentDBClusterIdentifier:
    Description: Identifier of the created DocumentDB cluster
    Value: !Ref DocumentDBCluster

