AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for an ECS Cluster with EC2 Instance

Parameters:
  ClusterName:
    Description: Name for the ECS cluster
    Type: String
    MinLength: 1
    MaxLength: 255
    ConstraintDescription: The cluster name must be between 1 and 255 characters.

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type

  ImageId:
    Description: ID of the Amazon Machine Image (AMI) to use
    Type: AWS::EC2::Image::Id
    ConstraintDescription: Must be a valid AMI ID

  SecurityGroupIds:
    Description: List of Security Group IDs for the EC2 instance
    Type: List<AWS::EC2::SecurityGroup::Id>
    ConstraintDescription: Must be a list of valid Security Group IDs

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID where the EC2 instance should be launched

Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ClusterName

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId  # Amazon Linux 2 AMI, replace with your desired AMI
      KeyName: node-key-pair
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetId: !Ref SubnetId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo ECS_CLUSTER=${ClusterName} >> /etc/ecs/ecs.config
      Tags:
        - Key: Name
          Value: !Ref ClusterName

Outputs:
  ECSInstanceID:
    Description: ID of the created EC2 instance
    Value: !Ref EC2Instance
