AWSTemplateFormatVersion: "2010-09-09"
Description: Secrets Manager Stack

Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MySecret
      Description: "My secret value"
      SecretString: '{"username": "myuser", "password": "mypassword"}'
