AWSTemplateFormatVersion: "2010-09-09"
Description: Secrets Manager Stack

Parameters:
  SecretName:
    Description: Name for the Secret
    Type: String
    MinLength: 1
    MaxLength: 255
  Description:
    Description: Description for the Secret
    Type: String
    MinLength: 1
    MaxLength: 255
  SecretValue:
    Description: Value for the Secret
    Type: String
    MinLength: 1
    MaxLength: 255

Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      Description: !Ref Description
      SecretString: !Ref SecretValue

Outputs:
  SecretArn:
    Value: !Ref Secret
    Description: ARN of the created Secrets Manager secret
