name: Deploy VPC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy VPC
      uses: aws-actions/aws-cloudformation-deploy@v2
      with:
        stack-name: MyVPCStack
        region: us-east-1
        template: ./templates/vpc.yaml
