name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: LambdaStack
          template: path/to/your/lambdaStack.yaml
          region: your-aws-region
          capabilities: CAPABILITY_IAM
          role-name: your-iam-role-name
          wait-for-stack: true
