name: Deploy Secrets Manager

on:
  workflow_dispatch:
    inputs:
      secret_name:
        required: true
        type: string
        description: secret name
      secret_description:
        required: true
        type: string
        description: secret description
      secret_value:
        required: true
        type: string
        description: secret value
      port_payload:
        required: true
        description:
          Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)
        type: string

jobs:
  deploy-cloudformation-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials 🔒
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ inputs.secret_name }}
          template: ./templates/secretsManager.yaml
          parameter-overrides: >-
            SecretName=${{ inputs.secret_name }},
            SecretDescription=${{ inputs.secret_description }},
            SecretValue=${{ inputs.secret_value }}
            
      - name: UPSERT Secret in Port
        uses: port-labs/port-github-action@v1
        with:
          identifier: ${{ inputs.secret_name }}
          title: ${{ inputs.secret_name }}
          team: "[]"
          icon: Secret
          blueprint: secrets_manager
          properties: |-
            {
              "secret_name": "${{ inputs.secret_name }}",
              "secret_description": "${{ inputs.secret_description }}",
              "secret_value": "${{ inputs.secret_value }}"
            }
          relations: "{}"
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          runId: ${{fromJson(inputs.port_payload).context.runId}}
