name: Create S3 Bucket

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      visibility:
        type: string
      port_payload:
        required: true
        description: Port's payload, including details for who triggered the action and general context
        type: string
  pull_request:
    branches:
      - main

jobs:
  createS3Bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Display Repository Contents
        run: ls -R

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: |
          cd templates  # Change to the directory where your Terraform files are
          terraform init

      - name: Terraform Apply
        run: |
          cd templates  # Change to the directory where your Terraform files are
          terraform apply -auto-approve

  createEntityInPort:
    runs-on: ubuntu-latest
    needs: createS3Bucket

    steps:
      - name: UPSERT Entity in Port
        uses: port-labs/port-github-action@v1
        with:
          identifier: ${{ github.repository_owner }}/my-s3-bucket
          blueprint: service
          properties: |-
            {
              "resource_definitions": "${{ github.server_url }}/${{ github.repository }}/${{ github.sha }}/main/"
            }
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
